import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '@/styles/global.module.css';
import Image from "next/image";
import home2 from '../images/home2.png';
import 'aos/dist/aos.css';
import SliderClients from './SliderClients';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className='home1'>
      <div className="container">
      <div className="row">
      <div className="col-md-12">
      </div>
      </div>
      </div>
      </section>
      <SliderClients />
      <section className='home3'>
      <div className="container">
      <div className="row">
      <div className="col-md-6">
      </div>
      <div className="col-md-6">
        <Image src={home2} alt='video' priority={true} />
      </div>
      </div>
      </div>
      </section>
    </div>
  )
}
